bot:
  name: mega_reminder_bot
  token: ${BOT_TOKEN}
web-hook:
  external-url: https://1aae0607.ngrok.io
  internal-url: http://localhost:8080
spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/reminder
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
logging:
  file: logs/reminder.log
  level:
    ru: debug
    net.iakovlev.timeshape: error
