bot:
  name: mega_reminder_bot
  token: ${BOT_TOKEN}
web-hook:
  external-url: https://46c80e54.eu.ngrok.io
  internal-url: http://localhost:8000
spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: jdbc:postgresql://localhost:5432/reminder
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
