package ru.gadjini.reminder.common;

public class CommandNames {

    private CommandNames() {}

    public static final String START_COMMAND_NAME = "start";
    public static final String HELP_COMMAND_NAME = "help";
    public static final String ACCEPT_FRIEND_REQUEST_COMMAND_NAME = "a";
    public static final String REJECT_FRIEND_REQUEST_COMMAND_NAME = "b";
    public static final String OK_COMMAND_NAME = "ok";
    public static final String SCHEDULE_COMMAND_NAME = "c";
    public static final String REMINDER_TIME_DETAILS_COMMAND_NAME = "d";
    public static final String DELETE_REMINDER_TIME_COMMAND_NAME = "e";
    public static final String USER_REMINDER_NOTIFICATION_WITH_TIME_HISTORY_NAME = "f";
    public static final String USER_REMINDER_NOTIFICATION_WITHOUT_TIME_HISTORY_NAME = "g";
    public static final String USER_REMINDER_NOTIFICATION_HISTORY_NAME = "h";
    public static final String USER_SETTINGS_COMMAND_HISTORY_NAME = "i";
    public static final String COMPLETE_REPEAT_REMINDER_COMMAND_NAME = "j";
    public static final String SKIP_REPEAT_REMINDER_COMMAND_NAME = "k";
    public static final String STOP_REPEAT_REMINDER_COMMAND_NAME = "l";
    public static final String GET_FRIEND_REQUEST_COMMAND_NAME = "m";
    public static final String FRIEND_REQUESTS_COMMAND_HISTORY_NAME = "n";
    public static final String FROM_ME_FRIEND_REQUESTS_HISTORY_NAME = "o";
    public static final String CANCEL_FRIEND_REQUEST_COMMAND_NAME = "p";
    public static final String DELETE_USER_REMINDER_NOTIFICATION_COMMAND_NAME = "q";
    public static final String FRIEND_DETAILS_COMMAND_NAME = "r";
    public static final String DELETE_REMINDER_NOTE_COMMAND_NAME = "s";
    public static final String CHANGE_TIMEZONE_COMMAND_HISTORY_NAME = "t";
    public static final String GO_BACK_CALLBACK_COMMAND_NAME = "u";
    public static final String REMINDER_DETAILS_COMMAND_NAME = "v";
    public static final String EDIT_REMINDER_COMMAND_NAME = "w";
    public static final String RECEIVER_REMINDER_COMMAND_NAME = "x";
    public static final String GET_COMPLETED_REMINDERS_COMMAND_NAME = "y";
    public static final String GET_ACTIVE_REMINDERS_COMMAND_NAME = "z";
    public static final String CUSTOM_REMINDER_TIME_COMMAND_NAME = "aa";
    public static final String DELETE_COMPLETED_REMINDERS_COMMAND_NAME = "ab";
    public static final String DELETE_REMINDER_COMMAND_NAME = "ac";
    public static final String CANCEL_REMINDER_COMMAND_NAME = "ad";
    public static final String POSTPONE_REMINDER_COMMAND_NAME = "ae";
    public static final String EDIT_REMINDER_TIME_COMMAND_NAME = "af";
    public static final String EDIT_REMINDER_TEXT_COMMAND_NAME = "ag";
    public static final String EDIT_REMINDER_NOTE_COMMAND_NAME = "ah";
    public static final String GET_REMINDERS_COMMAND_HISTORY_NAME = "ai";
    public static final String GET_FRIENDS_COMMAND_HISTORY_NAME = "aj";
    public static final String CREATE_FRIEND_REMINDER_COMMAND_NAME = "ak";
    public static final String DELETE_FRIEND_COMMAND_NAME = "al";
    public static final String COMPLETE_REMINDER_COMMAND_NAME = "am";
    public static final String CHANGE_FRIEND_NAME_COMMAND_NAME = "an";
    public static final String CREATE_REMINDER_KEYBOARD_COMMAND_NAME = "ao";
    public static final String READ_REMINDER_COMMAND_NAME = "ap";
    public static final String RETURN_REPEAT_REMINDER_COMMAND_NAME = "aq";
    public static final String DEACTIVATE_REMINDER_COMMAND_NAME = "ar";
    public static final String ACTIVATE_REMINDER_COMMAND_NAME = "as";
    public static final String ENABLE_COUNT_SERIES_COMMAND_NAME = "at";
    public static final String DISABLE_COUNT_SERIES_COMMAND_NAME = "au";
    public static final String SAVED_QUERY_COMMAND_HISTORY_NAME = "av";
    public static final String DELETE_SAVED_QUERY_COMMAND_NAME = "aw";
    public static final String CREATOR_REMINDER_COMMAND_NAME = "ax";
    public static final String CREATE_REMINDER_COMMAND_NAME = "ay";
    public static final String CALLBACK_DELEGATE_COMMAND_NAME = "ba";
    public static final String SUPPRESS_NOTIFICATIONS_COMMAND_NAME = "bb";
    public static final String TO_ME_FRIEND_REQUESTS_COMMAND_NAME = "bc";
    public static final String SEND_FRIEND_REQUEST_COMMAND_NAME = "bd";
    public static final String CREATE_CHALLENGE_COMMAND_NAME = "be";
    public static final String ACCEPT_CHALLENGE_COMMAND_NAME = "bf";
    public static final String REJECT_CHALLENGE_COMMAND_NAME = "bg";
    public static final String CHALLENGE_DETAILS_COMMAND_NAME = "bh";
    public static final String GO_TO_NEXT_COMMAND_NAME = "bi";
    public static final String GET_CHALLENGES_COMMAND_NAME = "bj";
    public static final String DELETE_CHALLENGE_COMMAND_NAME = "bk";
    public static final String GIVE_UP_COMMAND_NAME = "bl";
    public static final String EXIT_COMMAND_NAME = "bm";
    public static final String DELETE_ALL_COMMAND_NAME = "bn";
    public static final String COMPLETE_ALL_COMMAND_NAME = "bp";
    public static final String TIME_TRACKER_COMMAND_NAME = "bq";
}
