version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/dev:/etc/nginx/conf.d
    depends_on:
      - app
  app:
    container_name: app
    restart: always
    build: ../src/main/resources/public
    volumes:
      - ./logs:/app/logs
    expose:
      - "8000"
    ports:
      - "5005:5005"
    env_file:
      - app.env
    depends_on:
      - db
      - redis
  db:
    container_name: db
    image: postgres:10
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ../db.env
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    volumes:
      - ./data/redis:/opt/redis/data