version: '3'
services:
  app:
    container_name: app
    restart: always
    build: ../../../
    volumes:
      - ${HOME}/data/logs:/app/logs
    expose:
      - 8000
    ports:
      - 5005:5005
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    volumes:
      - ${HOME}/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../db.env
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    volumes:
      - ${HOME}/data/redis:/opt/redis/data
